openapi: 3.0.3
servers:
  - url: https://api.monobank.ua
info:
  title: Monobank open API
  version: v2112
  description:
    API для отримання інформації про виписки та стан особистого рахунку.
    Для надання доступу потрібно пройти авторизацію у особистому кабінеті https://api.monobank.ua/
    та отримати токен для персонального використання.


    Якщо у вас є запитання щодо роботи API, запрошуємо до ком'юніті у
    [Telegram-групі](https://t.me/joinchat/FiAEWhDf-QzTqM4wzEtffw).

    API недоступне для клієнтів до 16 років, дані за дитячими рахунами доступні з батьківського акаунту.

    Якщо у вас є сервіс і ви хочете централізовано приєднатися до API для надання послуг клієнтам,
    потрібно підключитися до [корпоративного API](/docs/corporate.html), що має більше можливостей.
    Якщо дані клієнтів не будуть надходити на ваші сервери або ви робите сервіс для своєї родини,
    використання корпоративного API необов'язкове. Розробка бібліотек або програм, які будуть
    використовувати клієнти особисто (дані клієнта не будуть проходити черeз вузли розробника),
    також не потребують використання корпоративного API.


    Це надасть змогу клієнтам monobank авторизуватись у вашому сервісі (наприклад, у фінансовому менеджері)
    для надання інформації про стан рахунку або виписки.


    У разі виявлення експлуатації цього API в якості корпоративного, банк залишає за собою право накласти санкції на компанію.
  x-logo:
    url: 'logo.png'
    altText: logo
paths:
  /bank/currency:
    get:
      tags:
        - Публічні дані
      summary: Отримання курсів валют
      description: Отримати базовий перелік курсів валют monobank. Інформація кешується та оновлюється не частіше 1 разу на 5 хвилин.
      responses:
        200:
          description: Інформація про курс валют
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyInfo'

  /personal/client-info:
    get:
      tags:
        - Клієнтські персональні дані
      summary: Інформація про клієнта
      description: Отримання інформації про клієнта та переліку його рахунків. Обмеження на використання функції не частіше ніж 1 раз у 60 секунд.
      parameters:
        - name: X-Token
          in: header
          schema:
            type: string
          required: true
          example: 'u3AulkpZFI1lIuGsik6vuPsVWqN7GoWs6o_MO2sdf301'
          description: Token для особистого доступу до API

      responses:
        200:
          description: Statement list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'

  /personal/webhook:
    post:
      tags:
        - Клієнтські персональні дані
      summary: Встановлення WebHook
      description: 'Встановлення URL користувача:

        - Для підтвердження коректності наданої адреси, на неї надсилається GET-запит.
        Сервер має відповісти строго HTTP статус-кодом 200, і ніяким іншим.
        Якщо валідацію пройдено, на задану адресу починають надсилатися POST запити з подіями.

        - Події надсилаються у наступному вигляді: POST запит на задану адресу у форматі
        `{type:"StatementItem", data:{account:"...", statementItem:{#StatementItem}}}`.
        Якщо сервіс користувача не відповість протягом 5с на команду, сервіс повторить
        спробу ще через 60 та 600 секунд. Якщо на третью спробу відповідь
        отримана не буде, функція буде вимкнута. Відповідь сервера має строго містити
        HTTP статус-код 200.'
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetWebHook'
      parameters:
        - name: X-Token
          in: header
          schema:
            type: string
          required: true
          description: Token для особистого доступу до API
      responses:
        200:
          description: ok

  /personal/statement/{account}/{from}/{to}:
    get:
      tags:
        - Клієнтські персональні дані
      summary: Виписка
      description:
        Отримання виписки за час від {from} до {to} часу в секундах в форматі Unix time
        Максимальний час за який можливо отримувати виписку 31 доба + 1 година (2682000 секунд)
        Обмеження на використання функції не частіше ніж 1 раз у 60 секунд.
      parameters:
        - name: X-Token
          in: header
          schema:
            type: string
          required: true
          description: Token для особистого доступу до API
        - name: account
          in: path
          schema:
            type: string
          required: true
          description: Ідентифікатор рахунку з переліку Statement list або 0 - дефолтний рахунок.
        - name: from
          in: path
          schema:
            type: string
          required: true
          example: '1546304461'
          description: Початок часу виписки.
        - name: to
          in: path
          schema:
            type: string
          required: false
          example: '1546306461'
          description: Останній час виписки (якщо відсутній, буде використовуватись поточний час).
      responses:
        200:
          description: Statement list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatementItems'
components:
  schemas:
    SetWebHook:
      type: object
      description: URL для надсиляння подій по зміні балансу рахунку
      properties:
        webHookUrl:
          example: 'https://mysomesite.copm/some_random_data_for_security'
          type: string
    UserInfo:
      type: object
      description: Опис клієнта та його рахунків.
      properties:
        clientId:
          description: Ідентифікатор клієнта (зівпадає з id для send.monobank.ua)
          type: string
          example: 3MSaMMtczs
        name:
          description: Ім'я клієнта
          type: string
          example: Мазепа Іван
        webHookUrl:
          description: URL для надсиляння подій по зміні балансу рахунку
          type: string
          example: https://mysomesite.copm/some_random_data_for_security
        permissions:
          description: Перелік прав, які які надає сервіс (1 літера на 1 permission).
          type: string
          example: 'psf'
        accounts:
          type: array
          description: Перелік доступних рахунків
          items:
            type: object
            properties:
              id:
                type: string
                description: Ідентифікатор рахунку
                example: kKGVoZuHWzqVoZuH
              sendId:
                type: string
                description: Ідентифікатор для сервісу https://send.monobank.ua/{sendId}
                example: uHWzqVoZuH
              balance:
                type: number
                format: int64
                description: Баланс рахунку в мінімальних одиницях валюти (копійках, центах)
                example: 10000000
              creditLimit:
                type: number
                format: int64
                description: Кредитний ліміт
                example: 10000000
              type:
                type: string
                description: Тип рахунку
                enum: [black, white, platinum, iron, fop, yellow, eAid]
                example: black
              currencyCode:
                type: number
                format: int32
                description: Код валюти рахунку відповідно ISO 4217
                example: 980
              cashbackType:
                type: string
                description: Тип кешбеку який нараховується на рахунок
                enum: [None, UAH, Miles]
                example: UAH
              maskedPan:
                type: array
                description: Перелік замаскованних номерів карт (більше одного може бути у преміальних карт)
                example: ['537541******1234']
              iban:
                type: string
                description: IBAN рахунку
                example: UA733220010000026201234567890
    StatementItems:
      type: array
      description: Перелік транзакцій за вказанний час
      items:
        type: object
        properties:
          id:
            type: string
            example: ZuHWzqkKGVo=
            description: Унікальний id транзакції
          time:
            type: number
            format: int64
            example: 1554466347
            description: Час транзакції в секундах в форматі Unix time
          description:
            type: string
            example: Покупка щастя
            description: Опис транзакцій
          mcc:
            type: number
            format: int32
            example: 7997
            description: Код типу транзакції (Merchant Category Code), відповідно ISO 18245
          originalMcc:
            type: number
            format: int32
            example: 7997
            description: Оригінальний код типу транзакції (Merchant Category Code), відповідно ISO 18245
          hold:
            type: boolean
            example: false
            description: Статус блокування суми (детальніше у [wiki](https://en.wikipedia.org/wiki/Authorization_hold))
          amount:
            type: number
            format: int64
            example: -95000
            description: Сума у валюті рахунку в мінімальних одиницях валюти (копійках, центах)
          operationAmount:
            type: number
            format: int64
            example: -95000
            description: Сума у валюті транзакції в мінімальних одиницях валюти (копійках, центах)
          currencyCode:
            type: number
            format: int32
            example: 980
            description: Код валюти рахунку відповідно ISO 4217
          commissionRate:
            type: number
            format: int64
            example: 0
            description: Розмір комісії в мінімальних одиницях валюти (копійках, центах)
          cashbackAmount:
            type: number
            format: int64
            example: 19000
            description: Розмір кешбеку в мінімальних одиницях валюти (копійках, центах)
          balance:
            type: number
            format: int64
            example: 10050000
            description: Баланс рахунку в мінімальних одиницях валюти (копійках, центах)
          comment:
            type: string
            example: За каву
            description: Коментар до переказу, уведений користувачем. Якщо не вказаний, поле буде відсутнім
          receiptId:
            type: string
            example: XXXX-XXXX-XXXX-XXXX
            description: Номер квитанции для check.gov.ua. Поле може бути відсутнім
          counterEdrpou:
            type: string
            example: '3096889974'
            description: ЄДРПОУ контрагента, присутній лише для елементів виписки рахунків ФОП
          counterIban:
            type: string
            example: UA898999980000355639201001404
            description: IBAN контрагента, присутній лише для елементів виписки рахунків ФОП

    CurrencyInfo:
      type: array
      description: Перелік курсів. Кожна валютна пара може мати одне і більше полів з  rateSell, rateBuy, rateCross.
      items:
        type: object
        properties:
          currencyCodeA:
            type: number
            format: int32
            example: 840
            description: Код валюти рахунку відповідно ISO 4217
          currencyCodeB:
            type: number
            format: int32
            example: 980
            description: Код валюти рахунку відповідно ISO 4217
          date:
            type: number
            format: int64
            example: 1552392228
            description: Час курсу в секундах в форматі Unix time
          rateSell:
            type: number
            format: float
            example: 27.0
          rateBuy:
            type: number
            format: float
            example: 27.2
          rateCross:
            type: number
            format: float
            example: 27.1
    Error:
      type: object
      properties:
        errorDescription:
          type: string
          description:
            Текст помилки для кінцевого користувача, для автоматичного
            оброблення потрібно аналізувати HTTP код відповіді (200, 404, 429 та інші)

tags:
  - name: Публічні дані
    description: Загальна інформація що надається без авторизації.
  - name: Клієнтські персональні дані
    description: Інформація, що надається тільки за наявстю token-а доступу, який клієнт може отримати в особистому кабінеті https://api.monobank.ua/
